name: Forger
version: '${version}'
author: mighty
main: com.cedricverlinden.forger.Forger
api-version: '1.20'

commands:
  forger:
    permission: forger.reload
    description: Main plugin command
    usage: /<command>
  item:
    permission: forger.manage.item
    description: Item management command
    aliases: [items]
    usage: /<command>
  recipe:
    permission: forger.manage.recipe
    description: Recipe management command
    aliases: [recipes]
    usage: /<command>
